# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 17e3864f6197815d0e7cd413abb6d89159b739adaedc2a9e4f93c4939ed7cc0ab0150f1fca7dfb6e89a6178d157efad172ea906d9adc4dce52266db3990e1f0a

test:
  secret_key_base: 9873138ff47f6c680ea8d4eb835623af7365d0ce0b2e20fcfa24bc0713f7ceea07db52a5ffe7bf9b0aca464dfc514b54947fd3bdfa88777e6bd2c955f73b43a9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
